language: c

jobs:
  include:
    - stage: compile
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # Need a newer compiler due to an apparent bug in gfortran-4.8
            # which breaks the getenv_allocating function
            - g++-5 gfortran-5
            - libblas-dev liblapack-dev
            - openmpi-bin openmpi-common libopenmpi-dev
      before_install:
        - export CTEST_OUTPUT_ON_FAILURE=True
        - export CC=gcc-5
        - export CXX=g++-5
        - export FC=gfortran-5
      script:
        # Clone the latest GRASP
        - env
        - git clone https://github.com/mortenpi/grasp.git ../grasp
        - source ../grasp/envset.sh
        - ./configure.sh --grasp-cmake
        - ${GRASP}/configure.sh --debug && cd ${GRASP}/build-debug/
        - make
        - make install
        - make test

    - stage: documentation
      addons:
        apt:
          sources:
            - mikepurvis/docs # Newer Doxygen
          packages:
            - doxygen graphviz
      script:
        - .ci/travis-deploy.sh
