language: c

jobs:
  include:
    - stage: compile
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # Need a newer compiler due to an apparent bug in gfortran-4.8
            # which breaks the getenv_allocating function
            - g++-4.9 gfortran-4.9
            - libblas-dev liblapack-dev
            - openmpi-bin openmpi-common libopenmpi-dev
      env:
        - |
          CTEST_OUTPUT_ON_FAILURE=True
          CC=gcc-4.9
          CXX=g++-4.9
          FC=gfortran-4.9
      script:
        # Clone the latest GRASP
        - env
        - git clone https://github.com/mortenpi/grasp.git ../grasp
        - source ../grasp/envset.sh
        - ./configure.sh --grasp-cmake
        - ${GRASP}/configure.sh --debug && cd ${GRASP}/build-debug/
        - make
        - make install
        - make test

    - stage: documentation
      before_install:
        - sudo add-apt-repository -y ppa:mikepurvis/docs # newer Doxygen
        - sudo apt-get update
        - sudo apt-get install -y doxygen graphviz
      script:
        - .ci/travis-deploy.sh
