name: Documentation

# branches: '*' only matches "main" branches, i.e. ones without a /, which would
# ensures that we don't run CI multiple times on pull requests --- we expect all
# feature branches to be namespaced as <prefix>/<branch>.
#
# However, currently we run with branches: '**' to also test feature branches
# because we do not necessarily open PRs for each of them.
on:
  push:
    branches: '**'
    tags: '**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: "Install dependencies"
      run: sudo apt-get install -y doxygen graphviz
    - name: "Build documentation"
      run: ./contrib/makedocs.sh
    - name: "Deploy documentation"
      #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env: # Set the secret as an input
        GITHUB_DEPLOY_KEY: ${{ secrets.DOXYGEN_DEPLOY_KEY }}
      run: ./contrib/deploydocs.sh
